#!/usr/bin/env bash
PGPASSWORD={{ ONTASK_POSTGRES_ROOT_PASSWORD }} psql -h {{ ONTASK_POSTGRES_HOST }} -p 5432 -U {{ ONTASK_POSTGRES_ROOT_USERNAME }} -c "CREATE USER {{ ONTASK_DB_USER }}"
PGPASSWORD={{ ONTASK_POSTGRES_ROOT_PASSWORD }} psql -h {{ ONTASK_POSTGRES_HOST }} -p 5432 -U {{ ONTASK_POSTGRES_ROOT_USERNAME }} -c "ALTER USER {{ ONTASK_DB_USER }} WITH PASSWORD '{{ ONTASK_POSTGRES_PASSWORD }}'"
PGPASSWORD={{ ONTASK_POSTGRES_ROOT_PASSWORD }} psql -h {{ ONTASK_POSTGRES_HOST }} -p 5432 -U {{ ONTASK_POSTGRES_ROOT_USERNAME }} -c "CREATE DATABASE {{ ONTASK_DB_NAME }} OWNER {{ ONTASK_DB_USER }}"
